// PREGNANCY
export const FETCH_PREGNANCY = 'FETCH_PREGNANCY';
export const FETCH_PREGNANCY_SUCCEEDED = 'FETCH_PREGNANCY_SUCCEEDED';
export const FETCH_PREGNANCY_FAILED = 'FETCH_PREGNANCY_FAILED';

// FOOD
export const FETCH_FOOD = 'FETCH_FOOD';
export const FETCH_FOOD_SUCCEEDED = 'FETCH_FOOD_SUCCEEDED';
export const FETCH_FOOD_FAILED = 'FETCH_FOOD_FAILED';

// BABYNAME
export const FETCH_BABYNAME = 'FETCH_BABYNAME';
export const FETCH_BABYNAME_SUCCEEDED = 'FETCH_BABYNAME_SUCCEEDED';

export const FETCH_BABYNAME_FAVOURITE = 'FETCH_BABYNAME_FAVOURITE';
export const FETCH_BABYNAME_FAILED = 'FETCH_BABYNAME_FAILED';

// DRINK
export const FETCH_DRINK = 'FETCH_DRINK';
export const FETCH_DRINK_SUCCEEDED = 'FETCH_DRINK_SUCCEEDED';
export const FETCH_DRINK_FAILED = 'FETCH_DRINK_FAILED';

// STORY
export const FETCH_STORY = 'FETCH_STORY';
export const FETCH_STORY_SUCCEEDED = 'FETCH_STORY_SUCCEEDED';

export const FETCH_STORY_MORE = 'FETCH_STORY_MORE';
export const FETCH_STORY_MORE_SUCCEEDED = 'FETCH_STORY_MORE_SUCCEEDED';

export const FETCH_STORY_FAVOURITE = 'FETCH_STORY_FAVOURITE';
export const FETCH_STORY_FAVOURITE_SUCCEEDED = 'FETCH_STORY_FAVOURITE_SUCCEEDED';

export const UPDATING_STORY_FAVOURITE = 'UPDATING_STORY_FAVOURITE';
export const UPDATING_STORY_FAVOURITE_SUCCEEDED = 'UPDATING_STORY_FAVOURITE_SUCCEEDED';

export const FETCH_STORY_FAILED = 'FETCH_STORY_FAILED';

// BALANCE
export const FETCH_BALANCE = 'FETCH_BALANCE';
export const FETCH_BALANCE_SUCCEEDED = 'FETCH_BALANCE_SUCCEEDED';
export const FETCH_BALANCE_FAILED = 'FETCH_BALANCE_FAILED';

//VACCINATION
export const FETCH_VACCINATION = 'FETCH_VACCINATION';
export const FETCH_VACCINATION_SUCCEEDED = 'FETCH_VACCINATION_SUCCEEDED';
export const FETCH_VACCINATION_FAILED = 'FETCH_VACCINATION_FAILED';

// COOKING
export const FETCH_COOKING = 'FETCH_COOKING';
export const FETCH_COOKING_SUCCEEDED = 'FETCH_COOKING_SUCCEEDED';

export const FETCH_COOKING_HINT = 'FETCH_COOKING_HINT';
export const FETCH_COOKING_HINT_SUCCEEDED = 'FETCH_COOKING_HINT_SUCCEEDED';

export const FETCH_COOKING_FAVOURITE = 'FETCH_COOKING_FAVOURITE';
export const FETCH_COOKING_FAVOURITE_SUCCEEDED = 'FETCH_COOKING_FAVOURITE_SUCCEEDED';

export const FETCH_COOKING_BY_SEARCH_TERM = 'FETCH_COOKING_BY_SEARCH_TERM';
export const FETCH_COOKING_BY_SEARCH_TERM_SUCCEEDED = 'FETCH_COOKING_BY_SEARCH_TERM_SUCCEEDED';

export const FETCH_COOKING_FAILED = 'FETCH_COOKING_FAILED';

// redux-saga connent internet
export const FETCH_CONNECTIVITY = 'FETCH_CONNECTIVITY';
export const FETCH_SUCCEEDED_CONNECTIVITY = 'FETCH_SUCCEEDED_CONNECTIVITY';